# Base on:
#   https://github.com/jacobalberty/unifi-docker
#   https://hub.docker.com/r/pihole/pihole

version: '3.7'
services:
  unifi_mongo:
    image: mongo:3.6
    container_name: unifi_mongo
    networks:
      - unifi
    restart: always
    volumes:
      - unifi_db:/data/db
      - unifi_dbcfg:/data/configdb
  controller:
    image: "jacobalberty/unifi:latest"
    container_name: unifi_controller
    depends_on:
      - unifi_mongo
    init: true
    networks:
      - unifi
    restart: always
    volumes:
      - unifi_dir:/unifi
      - unifi_data:/unifi/data
      - unifi_log:/unifi/log
      - unifi_cert:/unifi/cert
      - unifi_init:/unifi/init.d
      - unifi_run:/var/run/unifi
      # Mount local folder for backups and autobackups
      - ~/unifi_backup:/unifi/data/backup
    user: unifi
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 0
    environment:
      DB_URI: mongodb://unifi_mongo/unifi
      STATDB_URI: mongodb://unifi_mongo/unifi_stat
      DB_NAME: unifi
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
  unifi_logs:
    image: bash
    container_name: unifi_logs
    depends_on:
      - controller
    command: bash -c 'tail -F /unifi/log/*.log'
    restart: always
    volumes:
      - unifi_log:/unifi/log
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    networks:
      pihole:
        ipv4_address: 192.168.254.2
    volumes:
      - ./unbound/conf:/opt/unbound/etc/unbound/
    restart: always
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - ServerIP=192.168.254.3
      - TZ='Europe/Moscow'
      - DNS1='192.168.254.2#5053'
      - DNS2=''
      - WEBPASSWORD=${PIHOLE_WEB_PASSWORD:-piadmin}
    # Volumes store your data between container upgrades
    volumes:
      - '~/pihole/pihole/:/etc/pihole/'
      - '~/pihole/dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: always
    networks:
      pihole:
        ipv4_address: 192.168.254.3
    depends_on: 
       - unbound
volumes:
  unifi_db:
  unifi_dbcfg:
  unifi_data:
  unifi_log:
  unifi_cert:
  unifi_init:
  unifi_dir:
  unifi_run:

networks:
  unifi:
  pihole:
    driver: bridge
    ipam: 
      config: 
        - subnet: 192.168.254.0/29
